src/java/jsf/AliasesController.java
package jsf;

import jpa.entities.Aliases;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.AliasesFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("aliasesController")
@SessionScoped
public class AliasesController implements Serializable {

    private Aliases current;
    private DataModel items = null;
    @EJB
    private jpa.session.AliasesFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AliasesController() {
    }

    public Aliases getSelected() {
        if (current == null) {
            current = new Aliases();
            current.setAliasesPK(new jpa.entities.AliasesPK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private AliasesFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Aliases) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Aliases();
        current.setAliasesPK(new jpa.entities.AliasesPK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            current.getAliasesPK().setUserId(current.getUsers().getUserId());
            current.getAliasesPK().setPostId(current.getPosts().getPostId());
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AliasesCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Aliases) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            current.getAliasesPK().setUserId(current.getUsers().getUserId());
            current.getAliasesPK().setPostId(current.getPosts().getPostId());
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AliasesUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Aliases) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AliasesDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Aliases getAliases(jpa.entities.AliasesPK id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Aliases.class)
    public static class AliasesControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AliasesController controller = (AliasesController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "aliasesController");
            return controller.getAliases(getKey(value));
        }

        jpa.entities.AliasesPK getKey(String value) {
            jpa.entities.AliasesPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new jpa.entities.AliasesPK();
            key.setAlias(values[0]);
            key.setUserId(Integer.parseInt(values[1]));
            key.setPostId(Integer.parseInt(values[2]));
            return key;
        }

        String getStringKey(jpa.entities.AliasesPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getAlias());
            sb.append(SEPARATOR);
            sb.append(value.getUserId());
            sb.append(SEPARATOR);
            sb.append(value.getPostId());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Aliases) {
                Aliases o = (Aliases) object;
                return getStringKey(o.getAliasesPK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Aliases.class.getName());
            }
        }

    }

}

web/aliases/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAliasesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateAliasesLabel_aliasesPK_alias}" for="aliasesPK_alias" />
                    <h:inputText id="aliasesPK_alias" value="#{aliasesController.selected.aliasesPK.alias}" title="#{bundle.CreateAliasesTitle_aliasesPK_alias}" required="true" requiredMessage="#{bundle.CreateAliasesRequiredMessage_aliasesPK_alias}"/>
                    <h:outputLabel value="#{bundle.CreateAliasesLabel_users}" for="users" />
                    <h:selectOneMenu id="users" value="#{aliasesController.selected.users}" title="#{bundle.CreateAliasesTitle_users}" required="true" requiredMessage="#{bundle.CreateAliasesRequiredMessage_users}">
                        <f:selectItems value="#{usersController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateAliasesLabel_posts}" for="posts" />
                    <h:selectOneMenu id="posts" value="#{aliasesController.selected.posts}" title="#{bundle.CreateAliasesTitle_posts}" required="true" requiredMessage="#{bundle.CreateAliasesRequiredMessage_posts}">
                        <f:selectItems value="#{postsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{aliasesController.create}" value="#{bundle.CreateAliasesSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{aliasesController.prepareList}" value="#{bundle.CreateAliasesShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateAliasesIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/aliases/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAliasesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAliasesLabel_aliasesPK_alias}" for="aliasesPK_alias" />
                    <h:inputText id="aliasesPK_alias" value="#{aliasesController.selected.aliasesPK.alias}" title="#{bundle.EditAliasesTitle_aliasesPK_alias}" required="true" requiredMessage="#{bundle.EditAliasesRequiredMessage_aliasesPK_alias}"/>
                    <h:outputLabel value="#{bundle.EditAliasesLabel_users}" for="users" />
                    <h:selectOneMenu id="users" value="#{aliasesController.selected.users}" title="#{bundle.EditAliasesTitle_users}" required="true" requiredMessage="#{bundle.EditAliasesRequiredMessage_users}">
                        <f:selectItems value="#{usersController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditAliasesLabel_posts}" for="posts" />
                    <h:selectOneMenu id="posts" value="#{aliasesController.selected.posts}" title="#{bundle.EditAliasesTitle_posts}" required="true" requiredMessage="#{bundle.EditAliasesRequiredMessage_posts}">
                        <f:selectItems value="#{postsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{aliasesController.update}" value="#{bundle.EditAliasesSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditAliasesViewLink}"/>
                <br />
                <h:commandLink action="#{aliasesController.prepareList}" value="#{bundle.EditAliasesShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditAliasesIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/aliases/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListAliasesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListAliasesEmpty}" rendered="#{aliasesController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{aliasesController.items.rowCount > 0}">
                    <h:outputText value="#{aliasesController.pagination.pageFirstItem + 1}..#{aliasesController.pagination.pageLastItem + 1}/#{aliasesController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{aliasesController.previous}" value="#{bundle.Previous} #{aliasesController.pagination.pageSize}" rendered="#{aliasesController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{aliasesController.next}" value="#{bundle.Next} #{aliasesController.pagination.pageSize}" rendered="#{aliasesController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{aliasesController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAliasesTitle_aliasesPK_alias}"/>
                            </f:facet>
                            <h:outputText value="#{item.aliasesPK.alias}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAliasesTitle_users}"/>
                            </f:facet>
                            <h:outputText value="#{item.users}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAliasesTitle_posts}"/>
                            </f:facet>
                            <h:outputText value="#{item.posts}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{aliasesController.prepareView}" value="#{bundle.ListAliasesViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{aliasesController.prepareEdit}" value="#{bundle.ListAliasesEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{aliasesController.destroy}" value="#{bundle.ListAliasesDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{aliasesController.prepareCreate}" value="#{bundle.ListAliasesCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListAliasesIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/aliases/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewAliasesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAliasesLabel_aliasesPK_alias}"/>
                    <h:outputText value="#{aliasesController.selected.aliasesPK.alias}" title="#{bundle.ViewAliasesTitle_aliasesPK_alias}"/>
                    <h:outputText value="#{bundle.ViewAliasesLabel_users}"/>
                    <h:outputText value="#{aliasesController.selected.users}" title="#{bundle.ViewAliasesTitle_users}"/>
                    <h:outputText value="#{bundle.ViewAliasesLabel_posts}"/>
                    <h:outputText value="#{aliasesController.selected.posts}" title="#{bundle.ViewAliasesTitle_posts}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{aliasesController.destroyAndView}" value="#{bundle.ViewAliasesDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewAliasesEditLink}"/>
                <br />
                <h:commandLink action="#{aliasesController.prepareCreate}" value="#{bundle.ViewAliasesCreateLink}" />
                <br />
                <h:commandLink action="#{aliasesController.prepareList}" value="#{bundle.ViewAliasesShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewAliasesIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>